version: '3'
networks:
    gold-timer-network:
        name: gold-timer-network
services:
    postgres:
        image: postgres:14.7
        container_name: postgres-kzen
        restart: unless-stopped
        volumes:
            - ./db_data:/var/lib/postgresql/data/pgdata
        env_file:
            - .env
        ports:
            - '6008:5432'
        networks:
            - gold-timer-network

    graphql-engine:
        image: hasura/graphql-engine:v2.42.0
        container_name: graphql-engine-kzen
        ports:
            - '7008:8080'
        depends_on:
            - 'postgres'
        networks:
            - gold-timer-network
        restart: unless-stopped
        env_file:
            - .env
volumes:
    db_data:
